name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version of the function
        required: False

jobs:
  createrelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update version file
        id: version
        run: |
          # overwrite the version file with the new version
          echo "${{ inputs.VERSION }}" > VERSION
          echo "The contents of the VERSION file: $(cat VERSION)"
          echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "update version file"
          token: ${{ secrets.TOKEN }}
          title: "New version release"
          body: "Updating version file"
          branch: "update-version-${{ github.sha }}"

      - name: Create Release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v2.3.2
        with:
          name: "v${{ steps.version.outputs.VERSION }}"
          tag_name: ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }}
          generate_release_notes: true
          files: ${{ github.workspace }}/bin
