name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version of the function
        required: False


jobs:
  createrelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update version file
        id: version
        run: |
          # overwrite the version file with the new version
          echo "${{ inputs.VERSION }}" > VERSION
          echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: "update version file"
          title: "New version release"
          body: "Updating version file"
          branch: ${{ github.sha }}
          base: "main"
          labels: "jackaas"

      - name: Create Release
        if: ${{ success() }}
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v0.1.15
        with:
          name: "v${{ steps.version.outputs.VERSION }}"
          tag_name: ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }}
          body: |
            This is a new release of the Google Cloud Function called JackaaS.
          files: ${{ github.workspace }}/bin